### ISSUE TITLE
CocoaPods 0.36

### ISSUE THREAD

**Issue by lemonkey-medhelp** [medhelpintl/iphone_tn_test#1]
Not really an issue, just noticing the lock file was produced with CocoaPods 0.36 vs. 0.35.

Do you want to move to 0.36 yet?  I have locally on my machine at home but I haven't tested all of the apps yet.

With bundler and our Gemfile we can technically upgrade to 0.36 on our machines and still build the apps with 0.35 until we decide to officially upgrade the build process.

**Comment by lemonkey** [comment]
Wow this is old! Closing...
